services:

  result:
    image: result
    build:
      context: result
      dockerfile: Dockerfile

  vote:
    image: vote
    build:
      context: vote
      dockerfile: Dockerfile

  worker:
    image: worker
    build:
      context: worker
      dockerfile: Dockerfile

  seed:
    image: seed
    build:
      context: seed-data
      dockerfile: Dockerfile

  db:
    image: postgres

  
  redis:
    image: redis 

